import os
from pathlib import Path

ENABLE_OBSIDIAN_TOOLS = os.getenv("ENABLE_OBSIDIAN_TOOLS", False)
ENABLE_TRELLO_TOOLS = os.getenv("ENABLE_TRELLO_TOOLS", False)
ENABLE_CALENDAR_TOOLS = os.getenv("ENABLE_CALENDAR_TOOLS", False)
ENABLE_NEWS_SEARCH = os.getenv("ENABLE_NEWS_SEARCH", False)
ENABLE_WEB_PARSER = os.getenv("ENABLE_WEB_PARSER", False)

GOOGLE_CREDENTIALS_PATH = os.getenv("GOOGLE_CREDENTIALS_PATH", None)
GOOGLE_TOKEN_PATH = os.getenv("GOOGLE_TOKEN_PATH", None)
GOOGLE_CX_ID = os.getenv("GOOGLE_CX_ID", None)
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY", None)
GOOGLE_CALENDAR_SCOPES = ["https://www.googleapis.com/auth/calendar"]

OBSIDIAN_VAULT_PATH = Path(os.getenv("OBSIDIAN_VAULT_PATH", ""))
OBSIDIAN_DEFAULT_FOLDER = os.getenv("OBSIDIAN_DEFAULT_FOLDER", None)

SEMANTIC_SEARCH_ENABLED = os.getenv("SEMANTIC_SEARCH_ENABLED", False)
EMBEDDINGS_PATH = Path(os.getenv("EMBEDDINGS_PATH") or None)

TRELLO_API_KEY = os.getenv("TRELLO_API_KEY", None)
TRELLO_TOKEN = os.getenv("TRELLO_TOKEN", None)

LOG_PATH = Path(os.getenv("LOG_PATH"))
